[programs.localnet]
blog = "EZ6TPkmi1fpKmN5z6EcmUvkaVFMF8YfLHKCEbNJazuMR"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/geekycoder/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"